[package]
name = "crs"
version = "0.1.0"
description = "A utility crate that simplifies reuse of Common/Structured Reference String (CRS/SRS) from past trusted setup ceremonies, especially for SNARK"
authors = ["Alex Xiong <alex.xiong.tech@gmail.com>"]
edition = "2018"
repository = "https://github.com/alxiong/crs"
keywords = ["cryptography", "trusted setup", "zkSNARK", "CRS"]
categories = ["cryptography"]

[dependencies]
